force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseLine__c/PurchaseLine__c.object-meta.xml
<CustomObject>
    <label>Purchase Line</label>
    <nameField>
        <label>Purchase Line Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchase Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseLine__c/fields/ItemId__c.field-meta.xml
<CustomField>
    <fullName>ItemId__c</fullName>
    <label>ItemId</label>
    <referenceTo>Item__c</referenceTo>
    <relationshipLabel>Purchase Lines</relationshipLabel>
    <relationshipName>Purchase_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/triggers_handlers/ItemTriggerHandler.cls
public with sharing class ItemTriggerHandler {
  private static ItemSelector selector = new ItemSelector();

  public static void beforeDelete(List<Item__c> oldItems) {
    preventDeletionWithPurchaseHistory(oldItems);
  }

  private static void preventDeletionWithPurchaseHistory(
    List<Item__c> itemsToDelete
  ) {
    Map<Id, Item__c> itemsMap = new Map<Id, Item__c>(itemsToDelete);

    List<Item__c> itemsFromDb = selector.getItemsWithPurchaseLines(
      itemsMap.keySet()
    );

    for (Item__c dbItem : itemsFromDb) {
      if (!dbItem.Purchase_Lines__r.isEmpty()) {
        itemsMap.get(dbItem.Id)
          .addError(
            'Cannot delete this Item because it is part of a completed Purchase history.'
          );
      }
    }
  }
}