force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/AvailableQuantity__c.field-meta.xml
<CustomField>
    <fullName>AvailableQuantity__c</fullName>
    <label>AvailableQuantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Family 1</fullName>
            </value>
            <value>
                <fullName>Family 2</fullName>
            </value>
            <value>
                <fullName>Family 3</fullName>
            </value>
            <value>
                <fullName>Family 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Type 1, Type 2, Type 3, Type 4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/services/ItemCatalogService.cls
public with sharing class ItemCatalogService {
  private static IItemSelector selector = AppFactory.getItemSelector();
  private static IUserSelector userSelector = AppFactory.getUserSelector();
  private static IItemCatalogUnitOfWork unitOfWork = AppFactory.getItemCatalogUnitOfWork();

  public static List<ItemDTO> getFilteredItems(
    String type,
    String family,
    String searchTerm,
    Integer limitSize,
    Integer offsetSize
  ) {
    List<Item__c> items = selector.getItemsByFilters(
      type,
      family,
      searchTerm,
      limitSize,
      offsetSize
    );
    List<ItemDTO> dtos = new List<ItemDTO>();

    for (Item__c item : items) {
      dtos.add(new ItemDTO(item));
    }

    return dtos;
  }

  public static void createNewItem(ItemDTO itemDto) {
    Id currentUserId = UserInfo.getUserId();

    if (!userSelector.isUserManager(currentUserId)) {
      throw new SecurityException(
        'Access Denied: Only managers can create items.'
      );
    }

    String imageUrl = UnsplashImageService.fetchImageUrl(itemDto.name);

    Item__c newItem = new Item__c(
      Name = itemDto.name,
      Price__c = itemDto.price,
      Type__c = itemDto.type,
      Family__c = itemDto.family,
      AvailableQuantity__c = itemDto.availableQuantity,
      Description__c = itemDto.description,
      Image__c = imageUrl
    );

    unitOfWork.registerNew(newItem);
    unitOfWork.commitWork();
  }
}